# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6c4c587246b173efab9bf37ae66d97f6e4a90ea3ee93f44f1ad74cc09074e354174a5a0af7b6afc2c9dc04d22d39883b10fae12d7e980d4803a4f05f157ca0ef

test:
  secret_key_base: 777ad5b0cc9e23f8676def7575025bdfa7e10e8e438979defb7685ace9da0a6ada6104a586e097ec2c44bfd1494cbb7fa993035af225a29b9cb3056f65d0df06

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
